// <auto-generated />
using System;
using AWSServerlessFeedbackDiscipline.ContextBazaDeDate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AWSServerlessFeedbackDiscipline.Migratii
{
    [DbContext(typeof(FeedbackDisciplineContext))]
    [Migration("20230616212520_SchimbareNumeTabele")]
    partial class SchimbareNumeTabele
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AWSServerlessFeedbackDiscipline.Modele.AniDeStudiu", b =>
                {
                    b.Property<int>("id_ani_de_studiu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("anul_de_studiu")
                        .HasColumnType("longtext");

                    b.Property<int>("ciclul_de_studii")
                        .HasColumnType("int");

                    b.HasKey("id_ani_de_studiu");

                    b.ToTable("AniDeStudiu");
                });

            modelBuilder.Entity("AWSServerlessFeedbackDiscipline.Modele.Chestionare", b =>
                {
                    b.Property<int>("id_chestionar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("id_an_de_studiu")
                        .HasColumnType("int");

                    b.Property<int>("id_disciplina")
                        .HasColumnType("int");

                    b.Property<int>("id_program_de_studiu")
                        .HasColumnType("int");

                    b.Property<int>("id_student")
                        .HasColumnType("int");

                    b.Property<int>("id_tip_activitate")
                        .HasColumnType("int");

                    b.Property<int>("numar_activitate")
                        .HasColumnType("int");

                    b.HasKey("id_chestionar");

                    b.ToTable("Chestionare");
                });

            modelBuilder.Entity("AWSServerlessFeedbackDiscipline.Modele.CiclulDeStudii", b =>
                {
                    b.Property<int>("id_ciclu_de_studii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nume_ciclu_de_studii")
                        .HasColumnType("longtext");

                    b.HasKey("id_ciclu_de_studii");

                    b.ToTable("CiclulDeStudii");
                });

            modelBuilder.Entity("AWSServerlessFeedbackDiscipline.Modele.Discipline", b =>
                {
                    b.Property<int>("id_disciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("anul_de_studiu")
                        .HasColumnType("int");

                    b.Property<int>("ciclul_de_studii")
                        .HasColumnType("int");

                    b.Property<int>("nr_cursuri")
                        .HasColumnType("int");

                    b.Property<int>("nr_intalniri_proiect")
                        .HasColumnType("int");

                    b.Property<int>("nr_laboratoare")
                        .HasColumnType("int");

                    b.Property<int>("nr_seminare")
                        .HasColumnType("int");

                    b.Property<string>("nume_disciplina")
                        .HasColumnType("longtext");

                    b.Property<int>("program_de_studii")
                        .HasColumnType("int");

                    b.Property<int>("semestrul")
                        .HasColumnType("int");

                    b.HasKey("id_disciplina");

                    b.ToTable("Discipline");
                });

            modelBuilder.Entity("AWSServerlessFeedbackDiscipline.Modele.ProgrameStudiu", b =>
                {
                    b.Property<int>("id_programe_de_studiu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("id_ciclul_de_studii")
                        .HasColumnType("int");

                    b.Property<string>("nume_programe_de_studiu")
                        .HasColumnType("longtext");

                    b.HasKey("id_programe_de_studiu");

                    b.ToTable("ProgrameDeStudiu");
                });

            modelBuilder.Entity("AWSServerlessFeedbackDiscipline.Modele.TipuriActivitati", b =>
                {
                    b.Property<int>("id_tip_activitate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nume_activitate")
                        .HasColumnType("longtext");

                    b.HasKey("id_tip_activitate");

                    b.ToTable("TipuriActivitati");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roluri", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Utilizatori", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("LogareUtilizator", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoluriUtilizatori", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("TokenUtilizatori", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
